//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastro_Agendamentos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database_CadastroEntities4 : DbContext
    {
        public Database_CadastroEntities4()
            : base("name=Database_CadastroEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_CLIENTE> TB_CLIENTE { get; set; }
        public virtual DbSet<TB_ENDERECO> TB_ENDERECO { get; set; }
        public virtual DbSet<TB_META> TB_META { get; set; }
        public virtual DbSet<TB_PRODUTO> TB_PRODUTO { get; set; }
        public virtual DbSet<TB_TABELAPRECO> TB_TABELAPRECO { get; set; }
        public virtual DbSet<TB_VENDA> TB_VENDA { get; set; }
        public virtual DbSet<TB_VENDEDOR> TB_VENDEDOR { get; set; }
        public virtual DbSet<TB_GRUPO> TB_GRUPO { get; set; }
    }
}
