//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastro_Agendamentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PRODUTO
    {
        public string codigo { get; set; }
        public string descricao { get; set; }
        public string grupo { get; set; }
        public double custo { get; set; }
        public double valor_final { get; set; }
        public Nullable<int> qtd_produto { get; set; }
        public byte[] foto { get; set; }
        public string mime { get; set; }
    }
}
