//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastro_Agendamentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TABELAPRECO
    {
        public int codigo { get; set; }
        public string descricao { get; set; }
        public double valor { get; set; }
        public string cod_produto { get; set; }
    }
}
