//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastro_Agendamentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VENDA
    {
        public string codigo_produto { get; set; }
        public int codigo_cli { get; set; }
        public int qtd_produto { get; set; }
        public int desconto { get; set; }
        public double total { get; set; }
        public byte[] data { get; set; }
        public int id_ { get; set; }
    }
}
